[
  { "type" : "apple"},
  { "type" : "banana"},
  { "type" : "orange"},
  { "type" : "grape"},
  { "type" : "cutie"},
  { "type" : "bread"},
  { "type" : "corn"},
  { "type" : "carrot"},
  { "type" : "squash"},
  { "type" : "avacado"},
  { "type" : "apple juice"},
  { "type" : "canned apple"},
  { "type" : "chicken"},
  { "type" : "steak"},
  { "type" : "turky"},
  { "type" : "ham"},
  { "type" : "steak soup"},
  { "type" : "chicken soup"},
  { "type" : "orange juice"},
  { "type" : "grape juice"},
  { "type" : "mustard"},
  { "type" : "potatos"},
  { "type" : "mash potatos"},
  { "type" : "pea soup"},
  { "type" : "taco"},
  { "type" : "salt"},
  { "type" : "pepper"},
  { "type" : "corn chips"},
  { "type" : "tortilla chips"},
  { "type" : "tortilla"},
  { "type" : "chesse"},
  { "type" : "pepperoni"}
]